'use strict';
const fs=require('fs'),os=require('os'),path=require('path'),assert=require('assert/strict');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'switch-bridge-'));process.env.HOME=tmp;process.env.CLI_ACCOUNTS_ROOT=path.join(tmp,'accounts');
const store=require('../src/store');store.addProfile('claude','fixture',{shareSettings:false});let s=store.load();s.realBin.claude=process.execPath;store.save(s);
const {Engine}=require('../src/runtime/engine');let e=new Engine(path.join(tmp,'runtime'));
const owner={agentId:'main',sessionKey:'agent:main:discord:channel:fixture',sessionId:'session-1'};
const b=e.bindOpenClaw(owner);const r=e.submit({requestId:'external',mainKind:'openclaw',bindingId:b.id,projectPath:tmp,goal:'test',participants:[{tool:'claude',profileId:'fixture'}]});
let pending=e.openClawPending()[0];assert.equal(e.attempts(r.id)[0].state,'external_wait');assert.throws(()=>e.openClawDecide(r.id,{...owner,sessionId:'reset'},pending.attemptId,1,{}),/mismatch/);
const decision={kind:'delegate',summary:'one',reviews:[],delegations:[{participantId:'p1',goal:'read',resolvesTaskIds:[]}]};
e.openClawWake(r.id,pending.attemptId);assert.equal(e.root(r.id).status,'planning');e.db.close();e=new Engine(path.join(tmp,'runtime'));assert.equal(e.openClawPending().length,1);
e.openClawDecide(r.id,owner,pending.attemptId,1,decision);e.openClawDecide(r.id,owner,pending.attemptId,1,decision);assert.equal(e.tasks(r.id).length,1);assert.throws(()=>e.openClawDecide(r.id,owner,pending.attemptId,1,{...decision,summary:'different'}),/Conflicting/);
let t=e.tasks(r.id)[0];t.state='succeeded';t.resultVersion=1;t.result={success:true,summary:'done'};e.db.put('task',t);let ca=e.attempts(r.id).find(a=>a.role==='child');ca.state='succeeded';ca.processed=true;e.db.put('attempt',ca);e.tick();pending=e.openClawPending()[0];
assert.throws(()=>e.openClawDecide(r.id,owner,pending.attemptId,2,decision),/Stale/);
const complete={kind:'complete',summary:'verified',delegations:[],reviews:[{taskId:t.id,resultVersion:1,decision:'accepted',reason:'checked'}],finalResponse:'done'};
e.openClawDecide(r.id,owner,pending.attemptId,1,complete);assert.equal(e.root(r.id).status,'ready');assert.equal(e.root(r.id).finalDelivery,'pending');e.ack(r.id,1);assert.equal(e.root(r.id).status,'completed');
const r2=e.submit({requestId:'external-2',mainKind:'openclaw',bindingId:b.id,projectPath:tmp,goal:'test',participants:[{tool:'claude',profileId:'fixture'}]});const newer=e.bindOpenClaw({...owner,sessionId:'session-2'});e.suspendOpenClaw(b.id,'reset');assert.equal(e.db.get('bridge',newer.id).suspended,false);assert.equal(e.openClawPending().length,0);assert.throws(()=>e.authorizeOpenClaw(r2.id,owner),/mismatch/);e.cancel(r2.id);e.tick();assert.equal(e.root(r2.id).status,'cancelled');e.db.close();
console.log('PASS external main binding, no CLI main, durable pending/replay, scoped review, separate ack, reset and cancel');
(async()=>{
const {registerBridge}=await import('../plugins/openclaw/index.mjs');let nowSession='session-1',injections=0,wakes=0,decides=0,suspended=0,blocked=false;let tool, service;
const p={rootId:'r',attemptId:'a',generation:1,owner,nextWakeAt:0};
const events=[];
const api={logger:{warn(){}},pluginConfig:{},runtime:{agent:{session:{getSessionEntry:()=>({sessionId:nowSession})}},system:{enqueueSystemEvent(text,options){events.push({text,options});},requestHeartbeat(){assert.equal(events.length,wakes+1,'actionable event must precede every wake');wakes++;}}},session:{workflow:{async enqueueNextTurnInjection(){injections++;return blocked?{enqueued:false,id:''}:{enqueued:injections===1,id:'injection'};}}},registerTool(t){tool=t;},registerService(s){service=s;},lifecycle:{registerRuntimeLifecycle(){}}};
const client={ensureService:async()=>{},request:async(method)=>{if(method==='bridgePending')return[p];if(method==='bridgeSuspend')suspended++;if(method==='bridgeDecide')decides++;return {};}};
const bridge=registerBridge(api,client,store);bridge.startForTest();await bridge.poll();await bridge.poll();assert.equal(wakes,2);assert.equal(decides,0);blocked=true;await bridge.poll();assert.equal(wakes,2);nowSession='new';await bridge.poll();assert.equal(suspended,1);
assert.equal(events.length,2);assert.match(events[0].text,/action=get id=r/);assert.match(events[0].text,/attempt=a, generation=1/);assert.equal(events[0].options.sessionKey,owner.sessionKey);assert.equal(events[0].options.contextKey,'task:cli-account-switcher:a:1');assert.equal(events[0].options.replace,true);
const live=tool.create({...owner,assertInvocationCurrent(){throw Error('revoked');}});await assert.rejects(live.execute('x',{action:'decide',id:'r'}),/revoked/);assert.equal(decides,0);
await assert.rejects(live.execute('x',{action:'get'}),/Task id is required/);
nowSession=owner.sessionId;client.ensureService=async()=>{throw Error('ERR_TASK_PROTOCOL_MISMATCH fixture old service');};
const diagnostic=tool.create({...owner,assertInvocationCurrent(){}});
await diagnostic.execute('diagnostic',{action:'get',id:'r'});
await assert.rejects(diagnostic.execute('mutation',{action:'decide',id:'r'}),/PROTOCOL_MISMATCH/);
assert.equal(decides,0,'legacy service diagnosis cannot accidentally permit mutations');
console.log('PASS plugin duplicate/consumed wake never ACKs, injection policy blocks, reset blocks, revoked tool rejects');
const net=require('net'),clientRpc=require('../src/runtime/client');fs.mkdirSync(clientRpc.dir,{recursive:true});let bytes=0;
const server=net.createServer(c=>c.on('data',d=>{bytes+=d.length;}));await new Promise(r=>server.listen(clientRpc.socket,r));
let liveAuthority=true;const blockedWrite=clientRpc.request('bridgeDecide',{}, {beforeWrite(){if(!liveAuthority)throw Error('authority revoked before write');}});liveAuthority=false;
await assert.rejects(blockedWrite,/authority revoked/);await new Promise(r=>setTimeout(r,20));assert.equal(bytes,0);await new Promise(r=>server.close(r));
console.log('PASS RPC connection-time revocation sends zero bytes');
})().catch(e=>{console.error(e);process.exitCode=1;});
