'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  state: () => ipcRenderer.invoke('state'),
  openTasks: () => ipcRenderer.invoke('openTasks'),
  tasksAck: (id, version) => ipcRenderer.invoke('tasksAck', id, version),
  tasksStart: () => ipcRenderer.invoke('tasksStart'),
  tasksBindings: () => ipcRenderer.invoke('tasksBindings'),
  tasksList: () => ipcRenderer.invoke('tasksList'),
  tasksGet: (id) => ipcRenderer.invoke('tasksGet', id),
  tasksExternalList: () => ipcRenderer.invoke('tasksExternalList'),
  tasksExternalGet: (id) => ipcRenderer.invoke('tasksExternalGet', id),
  tasksOutput: (id, attemptId) => ipcRenderer.invoke('tasksOutput', id, attemptId),
  tasksSubmit: (input) => ipcRenderer.invoke('tasksSubmit', input),
  tasksChooseProject: (current) => ipcRenderer.invoke('tasksChooseProject', current),
  tasksCancel: (id) => ipcRenderer.invoke('tasksCancel', id),
  tasksResume: (id, request) => ipcRenderer.invoke('tasksResume', id, request),
  tasksRespond: (id, message) => ipcRenderer.invoke('tasksRespond', id, message),
  setActive: (tool, name) => ipcRenderer.invoke('setActive', tool, name),
  addProfile: (tool, name, opts) => ipcRenderer.invoke('addProfile', tool, name, opts),
  removeProfile: (tool, name) => ipcRenderer.invoke('removeProfile', tool, name),
  rename: (tool, name, newLabel) => ipcRenderer.invoke('rename', tool, name, newLabel),
  login: (tool, name) => ipcRenderer.invoke('login', tool, name),
  installShims: () => ipcRenderer.invoke('installShims'),
  registerPath: () => ipcRenderer.invoke('registerPath'),
  usageHook: (enable) => ipcRenderer.invoke('usageHook', enable),
  openHome: (tool, name) => ipcRenderer.invoke('openHome', tool, name),
  copy: (text) => ipcRenderer.invoke('copy', text),
  hide: () => ipcRenderer.invoke('hide'),
  resize: (h) => ipcRenderer.invoke('resize', h),
  setApiFetch: (on) => ipcRenderer.invoke('setApiFetch', on),
  apiRefresh: () => ipcRenderer.invoke('apiRefresh'),
  apiRefreshOne: (tool, name) => ipcRenderer.invoke('apiRefreshOne', tool, name),
  setApiInterval: (min) => ipcRenderer.invoke('setApiInterval', min),
  setUsageMode: (mode) => ipcRenderer.invoke('setUsageMode', mode),
  setDensity: (d) => ipcRenderer.invoke('setDensity', d),
  setZoom: (z) => ipcRenderer.invoke('setZoom', z),
  quit: () => ipcRenderer.invoke('quit'),
  onState: (cb) => ipcRenderer.on('state', (_e, s) => cb(s)),
});
